database:
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  host: ${DATABASE_HOST:localhost}
  name: ${DATABASE_NAME:infoessence}

openai:
  api_key: ${OPENAI_API_KEY}

jina:
  api_url: ${JINA_API_URL:https://r.jina.ai}

proxy:
  use_proxy: ${USE_PROXY:false}
  proxies: